[package]
name = "hledger-fmt"
version = "0.1.4"
edition = "2021"
description = "An opinionated hledger's journal files formatter."
repository = "https://github.com/mondeja/hledger-fmt"
authors = ["Álvaro Mondéjar Rubio"]
license = "MIT"
keywords = ["hledger", "journal", "formatter", "accounting"]
categories = ["command-line-utilities", "finance", "value-formatting"]
exclude = [
  ".editorconfig",
  ".github",
  "fuzz",
  ".pre-commit-config.yaml",
  ".pre-commit-hooks.yaml",
  ".markdown-link-check.json",
  ".gitignore",
  ".vscode",
]

[lib]
path = "src/lib.rs"

[[bin]]
name = "hledger-fmt"

[dependencies]
clap = { version = "4", default-features = false, features = ["std", "help"] }
walkdir = "2"
similar = "2"
anstream = { version = "0.6", optional = true }
anstyle = { version = "1", optional = true }

[features]
default = ["color"]
color = ["dep:anstream", "dep:anstyle", "clap/color"]

[profile.release]
strip = true
opt-level = "z"  # optimize for size
lto = true
codegen-units = 1
panic = "abort"

[workspace]
members = ["."]
