[package]
name = "hledger-fmt"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "hledger-fmt"

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2"
similar = "2"
colored = "2"
