[package]
name = "hledger-fmt"
version = "0.1.0"
edition = "2021"
description = "An opinionated hledger's journal files formatter."
repository = "https://github.com/mondeja/hledger-fmt"
keywords = [
  "hledger",
  "journal",
  "formatter",
  "accounting",
]

[lib]
path = "src/lib.rs"

[[bin]]
name = "hledger-fmt"

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2"
similar = "2"
colored = { version = "2", optional = true }

[features]
default = ["color"]
color = ["dep:colored"]
