cargo-features = [ "profile-rustflags" ]

[package]
name = "hledger-fmt"
version = "0.2.0"
edition = "2021"
description = "An opinionated hledger's journal files formatter."
repository = "https://github.com/mondeja/hledger-fmt"
authors = ["Álvaro Mondéjar Rubio"]
license = "MIT"
keywords = ["hledger", "journal", "formatter", "accounting"]
categories = ["command-line-utilities", "finance", "value-formatting"]
exclude = [
  ".editorconfig",
  ".github",
  "fuzz",
  ".pre-commit-config.yaml",
  ".pre-commit-hooks.yaml",
  ".markdown-link-check.json",
  ".gitignore",
  ".vscode",
  "lychee.toml",
]

[[bin]]
name = "hledger-fmt"

[dependencies]
clap.workspace = true
walkdir = "2"
similar = "2"
anstream = { version = "0.6", optional = true, default-features = false }
anstyle = { version = "1", optional = true, default-features = false }

[build-dependencies]
clap.workspace = true
clap_mangen = "0.2"

[features]
default = ["color", "auto-color"]
color = ["dep:anstream", "dep:anstyle", "clap/color"]
auto-color = ["anstream?/auto", "anstream?/wincon"]

[profile.release]
strip = true
opt-level = "z"  # optimize for size
lto = true
codegen-units = 1
panic = "abort"
rustflags = ["-Cpanic=abort", "-Zprofile-rustflags"]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["optimize_for_size", "panic_immediate_abort", "profile_rustflags"]
location-detail = "none"

[workspace]
members = ["."]

[workspace.dependencies]
clap = { version = "4", default-features = false, features = ["std", "help"] }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }{ archive-suffix }"
